#!/usr/bin/python3

import re
import sys

_, path = sys.argv

tables = {}

def replace_ref(match):
    return tables.setdefault(match[1], f't{len(tables)}')

lines = []
with open(path) as fh:
    for line in fh:
        if line.strip().startswith('--'):
            continue
        lines.append(re.sub(r'@ref\(([^)]*)\)', replace_ref, line))

for ref, table in tables.items():
    print(f'in/param/tables/{table}=_pos:{ref}:out/table')

print()
sys.stdout.writelines(lines)
