#!/bin/bash -ex

: ${PASSPHRASE?}

[[ -n $NESTED ]] || NESTED=1 exec ssh-agent "$0"

TARGET="${TARGET-tac.unit}"
REMOTE="${REMOTE-$USER@qx.knitinknit.com:src/skein}"

docker() {
    if type -P docker &> /dev/null; then
        command docker "$@"
    else
        command="$1"
        shift
        if [[ $command = run ]]; then
            set -- --userns keep-id "$@"
        fi
        set -- "$command" "$@"
        podman "$@"
    fi
}

rm -rf ci/gen/files
mkdir -p ci/gen/files ci/gen/state
cp *.* ci/gen/files

./ci/unit . '' "$TARGET" > ci/gen/plan

docker run --rm -u $UID --security-opt label=disable \
    -v $PWD/ci/gen:/root/src/nodes/gen:ro \
    -v $PWD/ci/gen/state:/root/src/nodes/state \
    ghcr.io/jmou/knit \
    knit run-plan gen/plan gen/files > ci/gen/invocation

curl -o ci/gen/identity https://calvin.mou.fo/user/skein/identity
chmod 600 ci/gen/identity
SSH_ASKPASS=ci/askpass ssh-add ci/gen/identity <<< "$PASSPHRASE"
SSH='ssh -o UserKnownHostsFile=ci/known_hosts'
rsync -a -e "$SSH" ci/gen/state/cas/ $REMOTE/.knit/cas/
$SSH ${REMOTE%%:*} run-hook $(<ci/gen/invocation)
