name: Run flow

on:
  push

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        USER: ${{ secrets.USER }}
      run: ./ci/run
    - run: >
        curl -f
        -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
        -d '{
          "state": "success",
          "target_url": "'"$(<ci/gen/url)"'",
          "description": "View data",
          "context": "Knitinknit"
        }'
        "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA"
